[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "visual-swarm"
version = "0.1.5"
authors = [
  { name="Anshul Patil", email="Aaprocks29@gmail.com" },
]
description = "A PSO library with a focus on visualization."
readme = "README.md"
license = { text = "MIT License" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.21, <2",
    "matplotlib>=3.5, <4"
]
[project.optional-dependencies]
gif = ["Pillow>=9.0"]
[tool.setuptools.packages.find]
where = ["."]
include = ["visual_swarm*"]
exclude = ["examples*", "tests*"]

[project.urls]
"Homepage" = "https://github.com/AnshulPatil29/visual-swarm"
"Repository" = "https://github.com/AnshulPatil29/visual-swarm"
"Bug Tracker" = "https://github.com/AnshulPatil29/visual-swarm/issues"