[tool.poetry]
name = "psiutils"
version = "0.1.59"
description = "Various TKinter utilities."
authors = ["Jeff <jeffwatkins2000@gmail.com>"]
readme = "README.md"
include = ["HISTORY.md", { path = "icons", format = "sdist" }]

[tool.poetry.dependencies]
python = "^3.11"
appdirs = "^1.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
