

[project]
name = "aspyx_event"
version = "0.9.0"
description = "Aspyx event framework"
authors = [{ name = "Andreas Ernst", email = "andreas.ernst7@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "aspyx-service>=0.10.4",
    "python-qpid-proton >=0.40.0",
    "stomp.py>=8.2.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
source = "src"

[tool.hatch.build.targets.wheel]
packages = ["src/aspyx_event"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.hatch.envs.test]
dependencies = [
  ".",
  "pytest",
  "pytest-cov",
  "pytest-asyncio",
  "anyio",
  "PyJWT"
]

[tool.hatch.metadata]
allow-direct-references = true
