[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chromologger"
version = "0.1.9.post1"
description = "Chromologger está diseñado para facilitar la creación de registros (logs) en aplicaciones desarrolladas con Python"
readme = { file = "README.md", content-type = "text/markdown", charset = "utf-8" }
license = "MIT"
authors = [{ name = "dev2forge", email = "support@dev2forge.software" }]
maintainers = [{ name = "tutosrive", email = "tutosrive@dev2forge.software" }]
keywords = [
    "logs",
    "dev2forge",
    "logging",
    "log",
    "logger",
    "exception logging",
    "error logging",
    "python logs",
    "file logger",
    "structured logs",
    "debugging",
    "monitoring",
    "chromologger",
    "simple logger",
    "python utility",
    "console logger",
    "developer tool",
    "log formatter",
    "log file"
]

requires-python = ">=3.8"

dependencies = [
    "chromolog==0.2.5"
]

classifiers=[
    "Development Status :: 5 - Production/Stable",

    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",

    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Debuggers",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Logging",
    "Topic :: Utilities",

    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Operating System :: OS Independent",
    "Environment :: Console",
    "Environment :: Other Environment",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = { find = { where = ["src"] } }

[project.urls]
"Homepage" = "https://docs.dev2forge.software/chromologger/"
"Repository" = "https://github.com/Dev2Forge/chromologger/"
"YouTube" = "https://www.youtube.com/@dev2forge"
"Issues" = "https://github.com/Dev2Forge/chromologger/issues/"