[package]
name = "cosmol_viewer_core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
eframe.workspace = true
serde_json.workspace = true
glam = { version = "0.30.3" , features = ["serde"] }
egui_extras.workspace = true
serde.workspace = true
bytemuck = "1.23.1"
web-sys = "0.3.77"
serde_repr = "0.1"
wasm-bindgen-futures = "0.4.50"
once_cell = "1.21.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui-winit.workspace = true
