[project]
name = "django-bigtrill"
version = "2.0.1"
description = "A simple Django package that will aid you to switch from using the default Django Auth User model to a custom User model in an existing Django project."

readme = "README.md"
license = "MIT"
authors = [
    { name = "Alexander Anyaegbunam", email = "alexander.any7@gmail.com" }
]
requires-python = ">=3"
keywords = ["django", "auth", "custom user", "migration", "bigtrill", "bigtrill migration", "default user model", "custom user model", "django custom user model", "django auth user model", "django user model migration", "existing project", "django existing project"]
dependencies = [
    "Django >= 3.2"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Framework :: Django"
]
urls = {"Homepage" = "https://github.com/alexander-any7/django-bigtrill.git"}

[project.scripts]
bigtrill-start = "bigtrill.start:main"