[project]
name = "pyprog-abubakaransari"  # MUST be lowercase, with hyphens not underscores (PyPI naming convention)
version = "0.1.2"
description = "Progress bars and spinners for terminal and notebooks"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [
  { name = "Muhammad Abubakar Siddique Ansari", email = "ansaricodes@gmail.com" }
]
dependencies = [
  "IPython==8.12.3",
  "colorama==0.4.6"
]
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["PyProg"]

[tool.setuptools.package-data]
"PyProg.assets.progress_bar" = ["*.json"]
"PyProg.assets.spinner" = ["*.json"]
