[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "my-common-utils"
version = "1.1.0"
description = "A selection of common utility functions, and useful APIs"
authors = ["Oliver Stoll <oliverstoll.berlin@gmail.com>"]
readme = "README.md"
packages = [
    { include = "common_utils", from = "src" }
]


[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1"
pyyaml = "^6.0.1"
notion-client = "^2"
pandas = "^2"
pytelegrambotapi = "^4.23.0"
selenium = "^4.29.0"
flask = "3.1.1"
authlib = "^1.5.1"
webdriver-manager = "^4.0.2"
undetected-chromedriver = "^3.5.5"
pydantic = "^2.11.4"
pytz = "^2025.2"
spotipy = "^2.25.1"
psutil = "^7.0.0"
pygame = "^2.6.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
ruff = "^0.1.13"
pytest = "^7.4.4"
mypy = "^1.8.0"
sphinx = "^7.2.6"
sphinx-rtd-theme = "^2.0.0"
sphinx-serve = "^1.0.1"
myst-parser = "^2.0.0"

[tool.poetry.group.windows.dependencies]
wmi = "^1.5.1"
pygetwindow = "^0.0.9"


[tool.ruff]
line-length = 100
[tool.ruff.lint.pylint]
max-statements = 16

[tool.mypy]
python_version = "3.11"
