[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deforum-flux"
version = "0.1.2"
description = "Flux backend for Deforum"
authors = [{name = "Deforum Inc", email = "hello@deforum.io"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.urls]
Homepage = "https://github.com/deforum/flux"
Repository = "https://github.com/deforum/flux"