[project]
name = "pymlt"
dynamic = ["version"]
description = "Python Machine Learning Toolkit"
authors = [
    { name = "Ben van Vliet", email = "benvliet@icloud.com" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
dependencies = [
#    "diskcache",
#    "envyaml",
#    "hyperopt",
#    "lightgbm",
#    "loguru",
#    "matplotlib",
#    "mlflow",
#    "numpy",
#    "pandas",
#    "polars",
#    "psycopg2",
#    "pyclean",
#    "python-box",
#    "python-dotenv",
#    "pyyaml",
#    "requests",
#    "ruff",
#    "scikit-learn",
#    "seaborn",
#    "sqlalchemy",
#    "tabulate",
#    "shap",
]
keywords = ['pymlt', 'machine learning', 'data science', 'toolkit', 'python']
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
repository = "https://github.com/benvliet/pymlt"
issues = "https://github.com/benvliet/pymlt/issues"
homepage = "https://pypi.org/project/pymlt/"

[project.optional-dependencies]
test = ["pytest>=6.0"]

[dependency-groups]
test = [
    "pytest>=6.0",
    "pytest-cov",
    "tox",
]
lint = [
    "ruff",
]
notebook = [
    "jupyter",
    "ipykernel",
    "nbconvert",
]

[build-system]
requires = ["setuptools>=64", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# leave empty to use the default versioning scheme

#[tool.setuptools.dynamic]
#version = {attr = "pymlt.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88
select = [
    "E",  # Errors
    "F",  # Pyflakes
    "I",  # Import-related issues
    "N",  # Naming conventions
    "Q",  # Quality checks
    "S",  # Style issues
    "T",  # Type hints
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning"
]

[tool.tox]
envlist = [
    "py27",
    "py37",
    "py38",
    "py39",
    "py310",
    "py311",
    "py312"
]

[tool.tox.testenv]
deps = ["pytest"]
commands = ["pytest"]

[tool.coverage]
source = ["src/pymlt"]
omit = [
    "*/tests/*",
    "*/__init__.py",
    "*/.venv/*",
]