[package]
name = "circuit_rs"
edition = "2024"
version = "0.3.3"
authors = ["Ian Quah<itq@uw.edu>"]

[lib]
name = "circuit_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
log = { version = "0.4", features = ["std", "serde"] }
tqdm = {version = "0.8"}
numpy = "0.25"
