[tool.poetry]
name = "flekspy"
version = "0.3.1"
description = "Python utilities for processing FLEKS data"
authors = ["Yuxi Chen <yuxichen@umich.edu>, Hongyang Zhou <hyzhou@umich.edu>"]
readme = "README.md"
packages = [{include = "flekspy", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
yt = "^4.3.0"
numpy = ">=1.26.4"
matplotlib = "^3.8.2"
scipy = "^1.14.1"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-benchmark = "^4.0.0"
pytest-cov = "^4.1.0"
jupyter = "^1.0.0"
myst-nb = "^1.0.0"
sphinx-autoapi = "^3.0.0"
sphinx-rtd-theme = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
