[tool.poetry]
name = "melia-fastapi"
version = "0.2.0"
description = "fastapi project generator and servicemanager"
authors = ["el hadji <elhadji.sarr@outlook.com>"]
readme = "README.md"
packages = [
    {include = "cli"},
    {include = "engine"},
    {include = "templates"}
]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.2.1"
jinja2 = "^3.1.6"

[tool.poetry.scripts]
melia = "cli.main:cli"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
