[project]
name = "mcp-markdown"
version = "0.3.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "刘松奇", email = "" }
]
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.11.0",
]

[project.scripts]
mcp-markdown = "mcp_markdown:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
