[project]
name = "mcp-email-client"
version = "0.1.3"
description = "A Model Context Protocol (MCP) server for sending and receiving emails, supporting IMAP/SMTP, with display name, reply, and robust error handling."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
 "fastmcp>=2.10.5",
]
[[project.authors]]
name = "0xFFLR"
email = "chnwine@qq.com"

[project.scripts]
mcp-email-client = "server:main"

[tool.setuptools]
py-modules = ["server"]
