[build-system]
requires = ["setuptools","setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["flask_bauto*"]
exclude = ["docs*", "tests*"]

[project]
name = "Flask-Bauto"
version = "0.1.2"
readme = "README.md"
dependencies = [
  'Flask-FEFset',
  'Flask-UXFab',
  'Flask-SQLAlchemy',
  'Flask-IAM'
]

[project.optional-dependencies]
fullstack = ['Bull-Stack']
dev = [
  'build',
  'twine',
]
