[project]
name = "openfda-mcp-server"
version = "0.1.3"
description = "A FastMCP server to expose drug safety analysis via OpenFDA API"
authors = [
  {name = "Praveen Bhati", email = "praveenb@incubxperts.com"}
]
keywords = ["openfda", "drug", "mcp", "llm"]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "mcp[cli]>=1.10.1",
  "uvicorn",
  "requests"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
openfda-mcp-server = "mcp_server_demo:main"
