[project]
name = "cps-learnai-mcp-demo"
version = "0.1.5"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "叽哩呱啦", email = "3425658642@qq.com" }
]
requires-python = ">=3.8"
dependencies = [
    "mcp[cli]>=1.11.0",
]

[project.scripts]
cps-learnai-mcp-demo = "cps_learnai_mcp_demo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
