[project]
name = "supply-demand"
version = "0.1.1"
authors = [{ name = "Sergey Shkatula", email = "sergey@ceil.dev" }]
description = "Functional dependency paradigm"
keywords = ["supply", "demand", "Supply-Demand", "functional"]
requires-python = ">=3.7"
license = "MIT"
readme = "README.md"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/supply_demand"]

[project.urls]
Homepage = "https://github.com/ceil-python/supply-demand"
