[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytelecast"
version = "0.1.1"
description = "A Telegram broadcast utility package with multiple database backends"
authors = [
{name = "Manji Devs", email = "ManjiStudios@outlook.com"},
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
"Programming Language :: Python :: 3",
"License :: OSI Approved :: MIT License",
"Operating System :: OS Independent",
]
dependencies = [
"python-telegram-bot>=20.0",
"pymongo>=4.0",
]