[project]
name = "dragon-ml-toolbox"
version = "3.12.0"
description = "A collection of tools for data science and machine learning projects."
authors = [
    { name = "Karl Loza", email = "luigiloza@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dependencies = [
    "numpy<2.0",
    "scikit-learn",
    "openpyxl", 
    "miceforest>=6.0.0",
    "plotnine>=0.12",
    "matplotlib",
    "seaborn",
    "pandas",
    "polars",
    "imbalanced-learn",
    "statsmodels",
    "ipython",
    "ipykernel",
    "notebook",
    "jupyterlab",
    "ipywidgets",
    "joblib",
    "xgboost",
    "lightgbm<=4.5.0",
    "shap",
    "tqdm>=4.0",
    "Pillow"
]

[project.urls]
Homepage = "https://github.com/DrAg0n-BoRn/ML_tools"
Changelog = "https://github.com/DrAg0n-BoRn/ML_tools/blob/master/CHANGELOG.md"

[project.optional-dependencies]
pytorch = [
    "torch",
    "torchvision"
]

gui = [
    "FreeSimpleGUI>=5.2"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ml_tools"]
