[project]
authors = [
  { email = "development@fluidattacks.com", name = "Fluid Attacks Engineering" },
]
description = "Python library for usage analytics"
license = "MPL-2.0"
name = "fluidattacks-tracks"
readme = "README.md"
requires-python = ">=3.11,<3.14"
version = "0.6.4"

dependencies = ["httpx>=0.28.1,<1"]

[dependency-groups]
dev = ["mypy==1.15.0", "ruff==0.12.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
