[build-system]
requires = ["meson-python", "cython", "numpy"]
build-backend = "mesonpy"

[project]
name = "sbmf"
version = "0.0.3"
authors = [
  { name="Matteo Alleman", email="mmallemmann@gmail.com" },
]
description = "Utilities for sparse and semi-binary matrix factorization"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT" 
license-files = ["LICEN[CS]E*"]
dependencies = ["numpy"]
