[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dspacelogs"
version = "0.1.4"
authors = [
  { name="MatusBeke" },
]
description = "A simple analyzer for DSpace log files"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: System :: Logging",
]
dependencies = [
    "pandas",
    "matplotlib",
    "seaborn",
]

[project.urls]
"Homepage" = "https://github.com/Matus-Beke/dspacelogs"

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["dspacelogs"]