[project]
name = "mandelbrot_synthesizer"
version = "0.1.3"
description = "This tool converts the escape time of each point in various fractals to a tone that can be used to make simple melodies"
authors = [
    {name = "Yahia"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
mandelbrot_synthesizer = "mandelbrot_synthesizer.MandelbrotSynthesizer:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
