[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "geosight"
version = "0.1.5"
authors = [
  { name = "Abdullah Ghifari" },
]
description = "Custom Grid with Pyspark Functions" # Optional but recommended
readme = "README.md" # Optional but recommended
requires-python = ">=3.7" # Optional but recommended
dependencies = [
  "python-geohash==0.8.5",
  "h3==3.7.7",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", # Example, change if needed
    "Operating System :: OS Independent",
]