[project]
name = "filter_url"
version = "0.2.2"
description = "A simple, fast, and configurable URL sensitive data filter"
authors = [
    { name = "Alex Semenyaka", email = "alex.semenyaka@gmail.com" },
]
dependencies = []
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
keywords = ["url", "filter", "filtering", "URL filtering", "logging"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: System :: Logging",
    "Topic :: Text Processing :: Filters",
]
[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "coveralls",
]

[project.urls]
Homepage = "https://github.com/alexsemenyaka/filter_url"
Repository = "https://github.com/alexsemenyaka/filter_url"
Issues = "https://github.com/alexsemenyaka/filter_url/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

