[project]
name = "bir_mcp"
version = "0.3.5"
description = "MCP server for BirBank"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "altair>=5.5.0",
    "atlassian-python-api>=4.0.4",
    "bidict>=0.23.1",
    "cachetools>=5.5.2",
    "detect-secrets>=1.5.0",
    "fastapi>=0.116.1",
    "fastmcp>=2.10.2",
    "gitpython>=3.1.44",
    "langchain>=0.3.26",
    "langchain-community>=0.3.27",
    "oracledb>=3.2.0",
    "pandas>=2.3.1",
    "py-consul>=1.6.0",
    "python-gitlab[graphql]>=6.1.0",
    "typer>=0.16.0",
    "vl-convert-python>=1.8.0",
]

[tool.uv]
package = true

[project.scripts]
bir_mcp = "bir_mcp.main:main"

[tool.ruff.lint]
# Ignore unused imports in __init__.py files
per-file-ignores = { "**/__init__.py" = ["F401"] }
