[project]
name = "yta-video-base"
version = "0.0.2"
description = "Youtube Autonomous Base Video Module."
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "yta_validation (>=0.0.1,<1.0.0)",
    "yta_numpy (>=0.0.1,<1.0.0)",
    "yta_file (>=0.0.1,<1.0.0)",
    "yta_colors (>=0.0.1,<1.0.0)",
    "yta_general_utils (>=0.0.1,<1.0.0)",
    "moviepy (>=0.0.1,<9.0.0)", # set valid version
    "numpy (>=0.0.1,<9.0.0)",   # set valid version
]

[tool.poetry]
packages = [{include = "yta_video_base", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
