[project]
name = "WeeLab"
version = "0.1.1"
description = "Unified control library for lab equipment (oscilloscopes, power supplies, lasers, etc.)"
authors = [{name = "Vsevolod Yeroshenko", email = "vsevolod.yeroshenko@weeroc.com"}]
license = "MIT"
#license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyserial",
    "pyvisa",
    "python-vxi11",
    "colorama",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
license-files = []
