[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "circuit-rs"
authors = [
  { name="Ian Quah", email="itq@uw.edu" },
]
description = "A library for doing efficient operations on neural circuits"
license = "MIT"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "numpy>=1.24.4",
]
[tool.maturin]
features = ["pyo3/extension-module"]

