[build-system]
requires = ["hatchling", "hatch-requirements-txt", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "pokie_score"
dynamic = [
        "dependencies",
        "version"
]
authors = [
  { name="Sammy Sharief", email="sharief2@illinois.edu" },
  { name = "Justine Zeghal", email = "" }
]
description = "Implemenation of the Pokie from Sharief et al. 2025"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = [
        "statistics",
        "machine learning",
        "pytorch"
]
classifiers=[
        "Development Status :: 1 - Planning",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3"
]

[project.urls]
Homepage = "https://github.com/SammyS15/Pokie"
Documentation = "https://github.com/SammyS15/Pokie"
Repository = "https://github.com/SammyS15/Pokie"
Issues = "https://github.com/SammyS15/Pokie/issues"

[project.optional-dependencies]
dev = [
    "pytest>=8.0,<9",
    "pytest-cov>=4.1,<5",
    "pytest-mock>=3.12,<4",
]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/pokie/_version.py"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.build.targets.wheel]
packages = ["src/pokie"]