[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]

name = "crossfilt"
description = "Tools to filter reads causing alignment bias in cross-species genomic comparisons"
license = "GPL-3.0-or-later"
readme = "README.md"
keywords = ["comparative genomics", "primate genetics", "alignment bias"]

dependencies = [
  "pysam",
  "bx-python"
]

requires-python = ">= 3.10"
version = "0.2.0"

authors = [
  {name = "Kenneth A Barr", email = "kenneth.a.barr@gmail.com"}
]
  
[project.scripts]
crossfilt-lift   = "crossfilt.liftover_bam:main"
crossfilt-split  = "crossfilt.split_bam:main"
crossfilt-filter = "crossfilt.identical_reads:main"

[project.urls]
Repository = "https://github.com/kennethabarr/CrossFilt.git"