[project]
name = "mcp-server-dartou"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dartou", email = "" }
]
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.10.1",
    "requests",
]

[project.scripts]
mcp-server-dartou = "mcp_server_dartou:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
