[project]
name = "abtranslate"
version = "0.1.28c21"
description = "Deployment friendly package supported with Argostranslate translation model"
readme = "README.md"
authors = [
    { name = "ichsantakwa", email = "ichsantakwa@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "ctranslate2>=3.17.0",
    "pandas>=2.3.0",
    "pytest>=8.4.1",
    "sentencepiece>=0.2.0",
    "stanza>=1.1.1",
]

[project.scripts]
abtranslate = "abtranslate:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
