[project]
name = "sdic_gxl"
version = "0.9.0"
description = ""
authors = [
    {name = "udo-bit",email = "enote_gxl@163.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=2.3.1,<3.0.0)",
    "oracledb (>=3.2.0,<4.0.0)",
    "sqlalchemy (>=2.0.41,<3.0.0)",
    "typer (>=0.16.0,<0.17.0)",
    "scipy (>=1.16.0,<2.0.0)"
]

[tool.poetry]
packages = [{include = "sdic", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
