[project]
name = "supernote-sync"
version = "0.2.2"
description = "Automatically sync Supernote notebooks and convert to PDF on local WiFi"
authors = [
    {name = "Jerome Boisvert-Chouinard",email = "github@jbchouinard.net"}
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.9,<4"
dependencies = [
    "supernotelib (>=0.6.2,<0.7.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "sqlalchemy (>=2.0.41,<3.0.0)",
    "tabulate (>=0.9.0,<0.10.0)",
    "reportlab (>=4.4.2,<5.0.0)"
]

[project.urls]
Homepage = "https://github.com/jbchouinard/supernote-sync"
Repository = "https://github.com/jbchouinard/supernote-sync"
Issues = "https://github.com/jbchouinard/supernote-sync/issues"

[tool.poetry]
name = "supernote-sync"
packages = [{include = "snsync"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[tool.poetry.scripts]
supernote-sync = "snsync.__main__:main"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["I"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
