[project]
name = "browserprofilecreator"
version = "0.1.1"
description = "Folder-based isolated browser profile generator."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
browserprofilecreator = "browserprofilecreator.cli:create"
create = "browserprofilecreator.cli:create"

[dependency-groups]
cli = [
    "click>=8.2.1",
]

[build-system]
requires = ["uv_build>=0.7,<0.8"]
build-backend = "uv_build"
