[project]
name = "matrixlibrary"
version = "0.1.0"
description = "A python package that provides tools to perform operations with matrices and vectors."
authors = [
    { name = "Rehaan Mahmood", email = "rehaanmd.310506@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
