[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "exobrain-actions-schemas"
dynamic = ["version"]
description = "Pydantic models for Exobrain Actions management (REST API clients or FastAPI/Flask web services)"
authors = [
    { name = "Laurent LAPORTE", email = "laurent.laporte.pro@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE.md" }
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "License :: Other/Proprietary License",
]
packages = [
  { include = "exobrain.actions.schemas" }
]
dependencies = [
    "pydantic>=2.11.7, <3",
]

[project.urls]
Documentation = "https://github.com/laurent-laporte-pro/exobrain-actions-schemas#readme"
Issues = "https://github.com/laurent-laporte-pro/exobrain-actions-schemas/issues"
Source = "https://github.com/laurent-laporte-pro/exobrain-actions-schemas"

[dependency-groups]
dev = [
    "coverage>=7.9.2",
    "mypy>=1.16.1",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.3",
    "twine>=6.1.0",
]

# -----------------------------------------------------------------------------
# Hatch configuration
# -----------------------------------------------------------------------------

[tool.hatch.version]
path = "src/exobrain/actions/schemas/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/exobrain"]

[tool.hatch.envs.types]
extra-dependencies = [
    "mypy>=1.16.1",
]
[tool.hatch.envs.types.scripts]
check = "mypy --namespace-packages --install-types --non-interactive  --package exobrain.actions.schemas  --package tests"

# -----------------------------------------------------------------------------
# Coverage configuration
# -----------------------------------------------------------------------------

[tool.coverage.run]
source_pkgs = ["exobrain.actions.schemas", "tests"]
branch = true
parallel = true
omit = [
    "src/exobrain/actions/schemas/__about__.py",
]

[tool.coverage.paths]
exobrain_actions_schemas = ["src/exobrain/actions/schemas", "*/exobrain-actions-schemas/src/exobrain/actions/schemas"]
tests = ["tests", "*/exobrain-actions-schemas/tests"]

[tool.coverage.report]
exclude_lines = [
    "no cov",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

# -----------------------------------------------------------------------------
# Mypy configuration
# -----------------------------------------------------------------------------

[tool.mypy]
python_version = "3.12"
namespace_packages = true
ignore_missing_imports = true
strict = true


# -----------------------------------------------------------------------------
# Ruff configuration
# -----------------------------------------------------------------------------

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"
