[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autodocz"
version = "0.1.9"
description = "A CLI tool to generate documents related to user projects"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name="Fatima Mansoor", email="fatima.mansoorali03@gmail.com" }]
keywords = ["readme", "directory", "cli"]
dependencies = ["groq", "python-dotenv"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.scripts]
autodocz = "autodocz.cli:main"