[project]
name = "loguru-dagster"
version = "0.1.0"
description = "A bridge to integrate Loguru logging with Dagster context.log."
authors = [{ name = "Ahmet Sahiner", email = "ahmethasimsahiner@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "loguru>=0.7.2",
    "dagster>=1.5.0",
]

[project.urls]
"Homepage" = "https://github.com/albertfast/loguru-dagster"
"Repository" = "https://github.com/albertfast/loguru-dagster"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
