[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blurpy"
dynamic = ["version"]
description = "A wrapper of Tekno's blur in Python ðŸ“¦"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Soumalya Das", email = "geniussantu1983@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/Soumalya Das/blurpy#readme"
Issues = "https://github.com/Soumalya Das/blurpy/issues"
Source = "https://github.com/Soumalya Das/blurpy"

[tool.hatch.version]
path = "src/blurpy/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/blurpy tests}"

[tool.coverage.run]
source_pkgs = ["blurpy", "tests"]
branch = true
parallel = true
omit = [
  "src/blurpy/__about__.py",
]

[tool.coverage.paths]
blurpy = ["src/blurpy", "*/blurpy/src/blurpy"]
tests = ["tests", "*/blurpy/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
