[tool.poetry]
name = "anc_data"
version = "0.1.4"
description = ""
authors = ["xxx AI Inc. <dev@xxx.ai>"]
license = "MIT"
readme = "README.md"
homepage = "https://sj-git.anuttacon.com/train-infra/anc_data"
repository = "https://sj-git.anuttacon.com/train-infra/anc_data"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.packages]]
include = "anc_data"
