[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yousif_raiyan_pip_package"
version = "1.6.13"
description = "Experimental kit for GRES and loader modules"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Raiyan", email = "raiyan0511@gmail.com" }]
requires-python = ">=3.7"
dependencies = [
  "numpy",
  "scipy",
  "mne",
  "pyedflib",
  "matplotlib",
  "pandas",
  "opencv-python",
  "torch",
  "torchvision",
  "joblib",
  "scikit-learn",
  "Pillow"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

[project.optional-dependencies]
dev = [
  "build",
  "twine",
  "bump2version"
]
