[project]
name = "ai-image-detector-messaging-schema"
version = "0.2.0"
description = ""
authors = [
    {name = "ycalk",email = "alosev752@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "faststream[rabbit] (>=0.5.47,<0.6.0)"
]

[tool.poetry]
packages = [{include = "messaging_schema", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
