[project]
name = "viuvsage"
version = "0.1.0"
description = "Sage: A Unified Project and Package Management System for C/C++ by viuvlabs"
authors = [
  {name = "Vishal Ahirwar", email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
dependencies = ["typer", "rich"]

[project.urls]
Homepage = "https://github.com/viuvlabs/sage"

[project.scripts]
sage = "viuvsage.cli:main"
