[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xray-uploader"
authors = [
    { name = "qun", email = "qun.chen@hexagon.com" }
]
description = "upload test results to xray."

requires-python = ">=3.0"
keywords = ["xray"]
license = { text = "MIT License" }
dependencies = [
    "requests==2.31.0"
]
version = "2.8.1"
readme = "README.md"

[project.scripts]
xray-uploader = "xray:main_cli"