[project]
name = "sneakydog-primitives-demo"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
authors = [
    {name = "dfz", email = "your.email@example.com"},
]
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "sqlalchemy>=2.0.41",
]

# [project.scripts]
# sneakydog-primitives-demo = "sneakydog_primitives_demo:main"
[project.urls]
"Homepage" = "https://github.com/yourusername/your-package"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
