[project]
name = "necbol"
version = "2.0.2"
license = "MIT"

authors = [
  { name="G1OJS", email="g1ojs@yahoo.com" },
]
description = "A plain language Python wrapper for NEC"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.0",
    "matplotlib"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/G1OJS/NECBOL"
Issues = "https://github.com/G1OJS/NECBOL/issues"

[tool.setuptools]
packages = ["necbol"]
license-files = ["LICENSE"]
