[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lotuschat-bot-sdk"
version = "0.1.25"
description = "SDK for interacting with LotusChat API"
readme = "README.md"
authors = [{ name = "Yuriko", email = "tunguyenanh@vccorp.vn" }]
license = { text = "MIT" }
dependencies = [
    "requests==2.32.4",
    "schedule==1.2.2",
    "flask==3.1.1",
    "pydantic==2.11.7",
    "aiohttp==3.12.14",
    "quart==0.20.0",
    "asgiref==3.9.1"
]

[project.urls]