[project]
name = "hkopenai_common"
version = "0.2.0"
description = "Common utilities for HK OpenAI MCP Servers"
requires-python = ">=3.9"
keywords = [ "mcp", "server", "utilities",]
classifiers = [ "Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
[[project.authors]]
name = "Neo Chow"
email = "neo@01man.com"

[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/hkopenai/hkopenai_common"
"Bug Tracker" = "https://github.com/hkopenai/hkopenai_common/issues"

[project.optional-dependencies]
dev = [ "pytest>=7.0", "pytest-mock",]

[tool.pytest.ini_options]
pythonpath = [ ".", "../..",]

[tool.setuptools.packages.find]
where = [ ".",]
include = [ "hkopenai_common",]
