[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jsoniq"
version = "0.1.0a8"
description = "Python edition of RumbleDB, a JSONiq engine"
requires-python = ">=3.11"
dependencies = [
    "pyspark==3.5.5"
]
authors = [
  {name = "Ghislain Fourny", email = "ghislain.fourny@inf.ethz.ch"},
  {name = "Abishek Ramdas"},
]
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["jsoniq", "spark", "apache-spark", "dataframe", "heterogeneous", "json", "query"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.11",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
jsoniq = ["jars/*.jar"]

[project.urls]
Homepage = "https://rumbledb.org"
Documentation = "https://rumble.readthedocs.io/en/latest/"
Repository = "https://github.com/RumbleDB/python-jsoniq.git"
"Bug Tracker" = "https://github.com/RumbleDB/python-jsoniq/issues"

[tool.black]
line-length = 88
